[package]
name = "qap-local-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stack-array = "0.4.1"
rand = "0.8.5"
num-traits = "0.2.14"
csv = "1.3.0"